# initial config
version: 1.0.{build}-{branch}

branches:
    only:
        - master

artifacts:
    - path: proj\Release\rel.zip
      type: zip

skip_commits:
    files:
        README.md
        .gitignore
        .github/*

platform: x64

configuration:
    - Release
   
image:
    - Visual Studio 2022

# cloning
clone_folder: c:/sledge

# installing
install:
    - git submodule update --init --recursive

# building
before_build:
    - cmd: mkdir proj
    - cmd: cd proj
    - cmd: cmake c:/sledge/ -G"Visual Studio 17 2022" -A x64 -T v143

build:
    parallel: true
    project: C:/sledge/proj/sledge.sln

after_build:
    - cmd: cd C:/sledge/proj/Release/
    - cmd: 7z a rel.zip sledge.dll mod.ps1 sledge.exe mods