# initial config
version: 1.0.{build}-{branch}
skip_tags: true
image: Visual Studio 2022

skip_commits:
    files:
        README.md
        .gitignore

# releases
artifacts:
    - path: proj\Release\Sledge.zip
      name: SledgeRelease
      type: zip

deploy:
    provider: GitHub
    release: sledge-v$(APPVEYOR_BUILD_VERSION)
    auth_token:
        secure: pAR0F1856OJePIBpQOxEe7xxWOVsNkF/T33PV5Z4YIU0qOGdIWOzcj0oqdtp4UCn
    repository: 44lr/sledge
    artifact: SledgeRelease
    on:
        branch: main

# cloning
clone_folder: c:/sledge

# installing
install:
    - git submodule update --init --recursive

# building
platform: x64

configuration:
    - Release

before_build:
    - cmd: mkdir proj
    - cmd: cd proj
    - cmd: cmake c:/sledge/ -G"Visual Studio 17 2022" -A x64 -T v143 -DOPENSSL_ROOT_DIR=C:/OpenSSL-v30-Win64

build:
    parallel: true
    project: C:/sledge/proj/sledge.sln

after_build:
    - cmd: cd C:/sledge/proj/Release/
    - cmd: 7z a Sledge.zip sledge.dll mod.ps1 sledge.exe mods ui ultralight